"""empty message

Revision ID: 68528a03ac1c
Revises: 14928c8041b0
Create Date: 2025-12-18 00:06:18.687603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68528a03ac1c'
down_revision = '14928c8041b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taglists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('vegan', sa.Boolean(), nullable=False),
    sa.Column('picante', sa.Boolean(), nullable=False),
    sa.Column('keto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receta_id')
    )
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['autor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('autor_id')

    op.drop_table('taglists')
    # ### end Alembic commands ###
