"""empty message

Revision ID: 7621669ab82f
Revises: 68528a03ac1c
Create Date: 2025-12-22 23:02:00.449258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7621669ab82f'
down_revision = '68528a03ac1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('foto_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('foto_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
